### ISSUE TITLE
PHP Build Error

### ISSUE THREAD

**Issue by brandontamm** [EmakinaFR/docker-magento2#16]
Main Error:
`
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
`

During the PHP build:
`Libraries have been installed in:
   /usr/src/php/ext/zip/modules
If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20160303/
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*

Installing the NodeSource Node.js 9.x repo...

Populating apt-get cache...

apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Hit:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
Reading package lists...

Installing packages required for setup: apt-transport-https lsb-release...

apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1

Confirming "stretch" is supported...

curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/stretch/Release'

Adding the NodeSource signing key to your keyring...

curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
Error executing command, exiting
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update -qq &&     apt-get install -y --no-install-recommends         bzip2         git         libcurl4-openssl-dev         libicu-dev         libfreetype6-dev         libjpeg-dev         libmcrypt-dev         libpng-dev         libxml2-dev         libxslt-dev         ssmtp &&     docker-php-ext-configure bcmath &&     docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ &&     docker-php-ext-install -j$(nproc)         bcmath         gd         intl         mcrypt         opcache         pdo_mysql         soap         xsl         zip &&     perl -pi -e "s/mailhub=mail/mailhub=maildev/" /etc/ssmtp/ssmtp.conf &&     usermod -u 1000 www-data &&     curl -sS https://deb.nodesource.com/setup_9.x | bash &&     apt-get install -y --no-install-recommends nodejs &&     npm install -g grunt-cli &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1`

**Comment by ajardin** [comment]
Hi @brandontamm,

Thanks for reporting the issue! It should be fixed now as Travis builds are successful again.
Let me know if you have any question. 😉
