### ISSUE TITLE
SSH socket sharing not working

### ISSUE THREAD

**Issue by Fulmenef** [EmakinaFR/docker-magento2#60]
**Describe the bug**
The new feature - #57 SSH socket sharing - doesn't seem to work when we have to deal with private repositories. When I try to run `composer require`  on a private repository inside the php container, my public key is not recognized while it is working outside the container.

**To Reproduce**
1. Go inside thee php container
2. Try to add private repository as a dependency
3. See error

**Expected behavior**
The dependency should be cloned without problem.

**Screenshots**
![Capture d’écran 2019-12-11 à 10 17 05](https://user-images.githubusercontent.com/17000257/70608580-a6120d00-1c00-11ea-8964-f6692ef2c98b.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.1
 - Docker version: Edge 2.1.6.0

Note: The issue can be reproduced both with and without passphrase on the SSH key.

**Comment by Fulmenef** [comment]
I found a fix for this issue, I think this only happen on an update base, once I made the fix I was not able to reproduce this issue any more.

1. Connect as root in the PHP container
2. Run the command `chmod 777 /run/host-services/ssh-auth.sock` to give access to the www-data user. I think the code `
RUN \
    mkdir -p /run/host-services/ && \
    chown www-data:www-data /run/host-services/` in the PHP Dockerfile is not used because the directory is owned by root.
3. Exit and connect as www-data with `make php`
4. Run `echo $SSH_AUTH_SOCK`, if the value is different of /run/host-services/ssh-auth.sock, then run `export SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock`

**Comment by ajardin** [comment]
It seems that the feature has been (finally) shipped with the latest version of Docker for Mac (cf. https://github.com/docker/for-mac/issues/410#event-2969099627). Could you check again? 🙂

**Comment by Fulmenef** [comment]
The socket is now shared with the stable version but on the first build the owner is root and therefore, cannot be used as www-data. 
I had to connect as root, change the user `chown www-data:www-data /run/host-services/ssh-auth.sock`.

I saw in the Dockerfile there's a line to change the owner of the directory but I think it is overwrited by the volume.

**Comment by ajardin** [comment]
It should be fixed by #70.
